#配置日志
logging:
#此处存放日志的路径
  level:
    com.baomidou: DEBUG

spring:
  jpa:
    # mysql 方言
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    dynamic:
      hikari:
        max-pool-size: 15
        min-idle: 5
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      #设置默认的数据源或者数据源组,默认值为master，修改 write-read 标识为读写库
      primary: master
      #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      strict: false 
      datasource:
        # 读写库，数据库相关配置  
        master_writeRead_51:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.1.12.51:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 1
        master_writeRead_52:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.1.12.52:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 1
        # 只读库
        slave_readOnly_53:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.1.12.53:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 1
        slave_readOnly_54:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.1.12.54:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
          username: root
          password: 1
